### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by trsh** [maZZZu/bmfr#3]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\BuildCustomizations\IntelOpenCL.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	bmfr	C:\Users\trsh\Downloads\bmfr-master\bmfr-master\opencl\bmfr.vcxproj	64

**Comment by maZZZu** [comment]
Seems like your Intel OpenCL driver installation is broken.

**Comment by trsh** [comment]
@maZZZu what has hard-coded link "C:\BuildCustomizations\IntelOpenCL.props" todo with my OpenCL drivers?

**Comment by maZZZu** [comment]
Please search the files in the repository. It is extended from: `<Import Project="$(INTELOCLSDKROOT)\BuildCustomizations\IntelOpenCL.props"/>`

**Comment by trsh** [comment]
@maZZZu I dont understand for what I have to search? `$(INTELOCLSDKROOT)\BuildCustomizations\IntelOpenCL.props` is for intel Graphics. I have GeForce.
