### ISSUE TITLE
Question about the albedo and color in the dataset

### ISSUE THREAD

**Issue by deadmarston** [maZZZu/bmfr#5]
Hi there,

Thank you for your great work.

I hold a question about the albedo in the dataset. If I understand correctly, is the albedo actually the diffuse albedo of material?
And if that's the case, how could you demodulate the albedo for a glossy material (glossy should be diffuse albedo + specular albedo) and for a specular material (specular albedo only)?

Thanks for your help:)

Cheers

**Comment by maZZZu** [comment]
Hi

I don't have access to that code anymore. So, I cannot check but I think we had either all ´specular albedo == diffuse albedo´ or all `specular albedo == 1.0`. At least I don't remember loading two textures for the albedos.

Hopefully this helps.

**Comment by deadmarston** [comment]
Hi there,

Thanks for your answer. I double-checked your paper and I think my problem is actually the multilayer materials problem, which you have mentioned in your paper.

Again, thanks for your help:)

Cheers
